# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-webauth}
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian V. Hughes"]
  s.date = %q{2010-04-27}
  s.description = %q{Rack middleware for Webauth authentication. Works with rack, sinatra and rails applications.}
  s.email = %q{brianvh@mac.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "examples/.gitignore",
     "examples/rack-app/.gitignore",
     "examples/rack-app/config.ru",
     "examples/rack-app/public/.gitignore",
     "examples/rack-app/tmp/.gitignore",
     "examples/rack-app/tmp/always_restart.txt",
     "examples/rails-app/.gitignore",
     "examples/rails-app/Rakefile",
     "examples/rails-app/app/controllers/application_controller.rb",
     "examples/rails-app/app/controllers/blocked_controller.rb",
     "examples/rails-app/app/controllers/home_controller.rb",
     "examples/rails-app/app/controllers/sessions_controller.rb",
     "examples/rails-app/app/helpers/application_helper.rb",
     "examples/rails-app/app/helpers/blocked_helper.rb",
     "examples/rails-app/app/helpers/home_helper.rb",
     "examples/rails-app/app/helpers/sessions_helper.rb",
     "examples/rails-app/app/views/blocked/index.html.erb",
     "examples/rails-app/app/views/home/index.html.erb",
     "examples/rails-app/app/views/sessions/new.html.erb",
     "examples/rails-app/config/boot.rb",
     "examples/rails-app/config/environment.rb",
     "examples/rails-app/config/environments/development.rb",
     "examples/rails-app/config/environments/production.rb",
     "examples/rails-app/config/environments/test.rb",
     "examples/rails-app/config/initializers/backtrace_silencers.rb",
     "examples/rails-app/config/initializers/inflections.rb",
     "examples/rails-app/config/initializers/mime_types.rb",
     "examples/rails-app/config/initializers/new_rails_defaults.rb",
     "examples/rails-app/config/initializers/session_store.rb",
     "examples/rails-app/config/locales/en.yml",
     "examples/rails-app/config/routes.rb",
     "examples/rails-app/public/404.html",
     "examples/rails-app/public/422.html",
     "examples/rails-app/public/500.html",
     "examples/rails-app/public/favicon.ico",
     "examples/rails-app/public/robots.txt",
     "examples/rails-app/script/about",
     "examples/rails-app/script/console",
     "examples/rails-app/script/dbconsole",
     "examples/rails-app/script/destroy",
     "examples/rails-app/script/generate",
     "examples/rails-app/script/performance/benchmarker",
     "examples/rails-app/script/performance/profiler",
     "examples/rails-app/script/plugin",
     "examples/rails-app/script/runner",
     "examples/rails-app/script/server",
     "examples/rails-app/tmp/.gitignore",
     "examples/sinatra-app/.gitignore",
     "examples/sinatra-app/app.rb",
     "examples/sinatra-app/config.ru",
     "examples/sinatra-app/public/.gitignore",
     "examples/sinatra-app/tmp/always_restart.txt",
     "examples/sinatra-app/views/login.erb",
     "lib/rack/webauth.rb",
     "lib/rack/webauth/authenticator.rb",
     "lib/rack/webauth/configuration.rb",
     "lib/rack/webauth/helpers.rb",
     "lib/rack/webauth/response.rb",
     "lib/rack/webauth/ticket.rb",
     "lib/rack/webauth/user.rb",
     "lib/rack/webauth/version.rb",
     "rack-webauth.gemspec",
     "script/console",
     "script/destroy",
     "script/generate",
     "spec/authenticator_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/brianvh/rack-webauth}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rack middleware for Webauth authentication.}
  s.test_files = [
    "spec/authenticator_spec.rb",
     "spec/spec_helper.rb",
     "examples/rails-app/app/controllers/application_controller.rb",
     "examples/rails-app/app/controllers/blocked_controller.rb",
     "examples/rails-app/app/controllers/home_controller.rb",
     "examples/rails-app/app/controllers/sessions_controller.rb",
     "examples/rails-app/app/helpers/application_helper.rb",
     "examples/rails-app/app/helpers/blocked_helper.rb",
     "examples/rails-app/app/helpers/home_helper.rb",
     "examples/rails-app/app/helpers/sessions_helper.rb",
     "examples/rails-app/config/boot.rb",
     "examples/rails-app/config/environment.rb",
     "examples/rails-app/config/environments/development.rb",
     "examples/rails-app/config/environments/production.rb",
     "examples/rails-app/config/environments/test.rb",
     "examples/rails-app/config/initializers/backtrace_silencers.rb",
     "examples/rails-app/config/initializers/inflections.rb",
     "examples/rails-app/config/initializers/mime_types.rb",
     "examples/rails-app/config/initializers/new_rails_defaults.rb",
     "examples/rails-app/config/initializers/session_store.rb",
     "examples/rails-app/config/routes.rb",
     "examples/sinatra-app/app.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rack>, [">= 1.1.0"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rack>, [">= 1.1.0"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

